
# ?????
server:
  port: 8888
  servlet:
    context-path: /blogweb
# ???????
spring:
  datasource:
    url: ENC(xYfIp+xwERxT6QrJ7T2bXK5tdEqqr00VwMbKMlEmH6oow8Ovqm6ofkJk20wlwsUISS81d8JjBWThNktPU89W/w==)
    username: ENC(z2zY/i+vbrd+PUM75jTCZQ==)
    password: ENC(g+v5pf3UHvoOhzp7ZdVdnu9k5tFoi74VJGM3afS3M0U=)
    driver-class-name: org.mariadb.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.blog.blogweb.entity
  global-config:
    db-config:
      id-type: auto
jasypt:
  encryptor:
    password: peytonlee
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator